# Generated by Django 3.2.6 on 2021-08-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name_project', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tile_task', models.CharField(max_length=50)),
                ('description_task', models.CharField(max_length=200)),
                ('imporant_task', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'Urgent')], default='0', max_length=1)),
                ('status_task', models.BooleanField(default=False)),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicApp.project')),
            ],
        ),
    ]
