# Generated by Django 3.2.6 on 2021-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_task',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
