# Generated by Django 3.2.6 on 2021-08-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0002_alter_task_id_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tile_task',
            new_name='title_task',
        ),
    ]
